# Numpy code practice

In [3]:
import numpy as np

In [5]:
arr= np.array([[1,2,3],
             [4,5,6]])

In [6]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
type(arr)

numpy.ndarray

In [9]:
arr.shape

(2, 3)

In [10]:
arr.ndim

2

In [11]:
print ("size of the array: ",arr.size)

size of the array:  6


In [12]:
print ("data type is ",arr.dtype)

data type is  int32


## Creating arrays using functions

In [13]:
a = np.array([[1,2,3],[4,5,6]], dtype='float')

In [15]:
print ("array from list :\n",a)

array from list :
 [[1. 2. 3.]
 [4. 5. 6.]]


In [16]:
b= np.array((1,2,3))

In [17]:
print("array from tupple:\n",b)

array from tupple:
 [1 2 3]


In [19]:
c= np.zeros((3,4))

In [20]:
print("zero matrix:\n",c)

zero matrix:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
d=np.ones((5,5))

In [22]:
print("ones matrix:\n",d)

ones matrix:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [23]:
e =np.eye(8,)

In [24]:
print("identity matrix:\n",e)

identity matrix:
 [[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [25]:
f =np.arange(0,100,2)

In [26]:
f

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [27]:
g = np.linspace(100,101,50)

In [28]:
g

array([100.        , 100.02040816, 100.04081633, 100.06122449,
       100.08163265, 100.10204082, 100.12244898, 100.14285714,
       100.16326531, 100.18367347, 100.20408163, 100.2244898 ,
       100.24489796, 100.26530612, 100.28571429, 100.30612245,
       100.32653061, 100.34693878, 100.36734694, 100.3877551 ,
       100.40816327, 100.42857143, 100.44897959, 100.46938776,
       100.48979592, 100.51020408, 100.53061224, 100.55102041,
       100.57142857, 100.59183673, 100.6122449 , 100.63265306,
       100.65306122, 100.67346939, 100.69387755, 100.71428571,
       100.73469388, 100.75510204, 100.7755102 , 100.79591837,
       100.81632653, 100.83673469, 100.85714286, 100.87755102,
       100.89795918, 100.91836735, 100.93877551, 100.95918367,
       100.97959184, 101.        ])

In [29]:
h=f.reshape(5,5,2)

In [30]:
h

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10],
        [12, 14],
        [16, 18]],

       [[20, 22],
        [24, 26],
        [28, 30],
        [32, 34],
        [36, 38]],

       [[40, 42],
        [44, 46],
        [48, 50],
        [52, 54],
        [56, 58]],

       [[60, 62],
        [64, 66],
        [68, 70],
        [72, 74],
        [76, 78]],

       [[80, 82],
        [84, 86],
        [88, 90],
        [92, 94],
        [96, 98]]])

In [31]:
i=e.flatten()

In [32]:
i

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

In [42]:
e


array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

## Index

In [34]:
temp=e[:4,4:]

In [35]:
temp

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
temp=e[:4:2,4::3]

In [37]:
temp

array([[0., 0.],
       [0., 0.]])

In [38]:
cond = e>0
temp=e[cond]

In [39]:
temp

array([1., 1., 1., 1., 1., 1., 1., 1.])

## Operations

In [40]:
h=arr+1


In [41]:
h

array([[2, 3, 4],
       [5, 6, 7]])

In [44]:
i=arr-10
j=arr*10
k=arr**3


In [45]:
i

array([[-9, -8, -7],
       [-6, -5, -4]])

In [46]:
j

array([[10, 20, 30],
       [40, 50, 60]])

In [47]:
k

array([[  1,   8,  27],
       [ 64, 125, 216]], dtype=int32)

In [48]:
arr*=3

In [49]:
arr

array([[ 3,  6,  9],
       [12, 15, 18]])