# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [5]:
import numpy as np
np.version?

Object `np._version_` not found.


#### 3. Create a null vector of size 10

In [2]:
import numpy as np
arr = np.zeros((10,10))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 4.  How to find the memory size of any array

#### 5.  How to get the documentation of the numpy add function from the command line? 

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [3]:
import numpy as np
arr = np.zeros((10,))
arr[4]=1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49

In [7]:
import numpy as np
arr = np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last)

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
import numpy as np
arr = np.arange(0,9)
arr= arr.reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [4]:
import numpy as np
arr = np.nonzero([1,2,0,0,4,0])
print(arr)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix

In [10]:
import numpy as np
a = np.eye(3,)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [11]:
import numpy as np
arr = np.random.random((3,3,3))
arr

array([[[0.53081543, 0.21400573, 0.05494973],
        [0.92530166, 0.1592827 , 0.83024174],
        [0.85482753, 0.84764202, 0.26289909]],

       [[0.23237829, 0.89164814, 0.43398753],
        [0.06625058, 0.71415015, 0.94263786],
        [0.63047666, 0.13163529, 0.31129593]],

       [[0.61961552, 0.72210274, 0.04848562],
        [0.83641259, 0.43627263, 0.83973296],
        [0.24346525, 0.48683055, 0.50674286]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [3]:
import numpy as np
arr = np.random.random((10,10))
print(arr)
print("\n ",arr.min())
print("\n",arr.max())


[[0.42689295 0.65173035 0.22237941 0.99350457 0.89161135 0.14556465
  0.84186307 0.15780833 0.1522071  0.36152092]
 [0.59237416 0.44862877 0.61044094 0.17902133 0.70971154 0.01482298
  0.69596546 0.18538547 0.06945469 0.28687412]
 [0.80002823 0.78940724 0.21279968 0.55812477 0.76884154 0.30756747
  0.61571418 0.81170388 0.6645384  0.49137536]
 [0.76864389 0.92946061 0.51077376 0.22172876 0.37162153 0.60285667
  0.51355601 0.92506207 0.68064419 0.38309802]
 [0.55984218 0.20030738 0.58662076 0.14348835 0.54547723 0.70480909
  0.36578705 0.70355265 0.29627364 0.01419965]
 [0.63957301 0.64752431 0.05618753 0.06278975 0.91854945 0.78506517
  0.8922217  0.35682851 0.60203    0.80959023]
 [0.73737793 0.91002111 0.09286091 0.58680462 0.1233878  0.11907293
  0.91715502 0.94697287 0.11385278 0.65634659]
 [0.05793863 0.84671623 0.45685155 0.6477017  0.20823941 0.38339552
  0.7469258  0.53045546 0.11494144 0.13142645]
 [0.42428632 0.89679471 0.4070088  0.54460059 0.470893   0.25442958
  0.13241519

#### 14. Create a random vector of size 30 and find the mean value

In [7]:
a = np.random.random(10,)

print (a.mean())

0.6378709299469622


#### 15. Create a 2d array with 1 on the border and 0 inside

#### 16. How to add a border (filled with 0's) around an existing array?

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [17]:
arr = np.diag(1+np.arange(4), k = -1)
print (arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?